Monday-Morning/project-tahiti

- client/src/components/article/SidePanel.js
- client/src/components/article/TableOfContent.js
> fix: sticky issue in the article page

- client/src/graphql/queries/article/getArticleByOldID.js
- client/src/pages/article/[...article].jsx
- Add query for getArticleByOldID
- Redirect old links to new links
❤️Thank you!
> feat(article): redirect old links to new links

- client/src/pages/[category]/[subCategory].jsx
- client/src/pages/[category]/index.jsx
- client/src/pages/article/[...article].jsx
-> null check for article, category and sub-category pages
❤️Thank you!
> fix: null check for article, category and sub-category pages

- client/src/components/widgets/Squiggles.js
Fixes
squiggle text-align issue fix for the mobile screen. 
❤️Thank you!
> fix(styles): squiggle text align

- client/package.json
- client/src/graphql/queries/subcategory/countOfArticlesBySubCategory.js
- client/src/pages/[category]/[subCategory].jsx
- client/src/screens/SubCategory.js
- client/yarn.lock
Fixes
add pagination in the subcategory page.
❤️Thank you!
> feat: add pagination in subcategory

- client/src/components/widgets/Squiggles.js
> fix(style):fix squiggle stack issue

- client/src/components/marginals/Footer.js
Fixes
Before
After
❤️Thank you!
> fix(style): add responsiveness to footer

- client/src/pages/[category]/[subCategory].jsx
> fix: add null check

- client/src/components/widgets/article/SmallArticleCard.js
> fix: small card image not fitting properly

- client/src/pages/[category]/[subCategory].jsx
- client/src/pages/[category]/index.jsx
Fixes #203 #202 
looping and filter on an undefined object 
❤️Thank you!
> fix(bug): looping and filter on undefined object 

- client/src/components/shared/button/ScrollToTopButton.js
Fixes 
Before
After
❤️Thank you!
> fix: positioning issue of scroll button

- client/src/components/widgets/article/RegularArticleCard.js
- client/src/components/widgets/article/SmallArticleCard.js
> style: change cursor type to pointer of article cards

- client/src/components/article/SidePanel.js
- client/src/components/article/SidePanelMobile.js
- client/src/pages/article/[...article].jsx
- client/src/screens/Article.js
Fixes #201 
Add material UI sidebar in mobile view 
❤️Thank you!
> fix: side panel close issue

- client/src/components/portfolio/Backlink.js
- client/src/components/portfolio/UserCard.js
- client/src/components/portfolio/Works.js
- client/src/components/shared/MarkdownWrapper.js
- client/src/components/widgets/article/RegularArticleCard.js
- client/src/graphql/fragments/article/basicArticleData.js
- client/src/graphql/queries/article/getListOfArticles.js
- client/src/graphql/queries/user/getUserById.js
- client/src/pages/portfolio/[userId]/[name].jsx
- client/src/screens/Portfolio.js
Fixes #119 
Created portfolio page for the content team.
ready to deploy
❤️Thank you!
> feat: add portfolio page

- client/src/utils/getRoutes.js
Fixes
Changing the subcategory name of CWC
❤️Thank you!
> fix: cwc subcategory name change

- client/src/screens/Category.js
> fix: variable not defined error

- client/src/components/marginals/DesktopNavbar.js
- client/src/components/marginals/Footer.js
- client/src/components/marginals/TopBar.js
- client/src/screens/About.js
- client/src/screens/Article.js
- client/src/screens/Category.js
- client/src/screens/Contact.js
- client/src/screens/Expressions.js
- client/src/screens/Guide.js
- client/src/screens/Home.js
- client/src/screens/Live.js
- client/src/screens/PhotoStory.js
- client/src/screens/Podcast.js
- client/src/screens/Policy.js
- client/src/screens/SearchPage.jsx
- client/src/screens/SubCategory.js
- client/src/screens/UserProfile.js
> fix(style): max width of the app

- client/src/components/article/Header.js
> fix: author image and sidebar overlap issue

- client/src/components/widgets/article/SmallArticleCard.js
Fixes
author id issue in small article card
❤️Thank you!
> fix: author id issue in small article card

- client/src/components/marginals/DesktopNavbar.js
- client/src/components/marginals/Footer.js
- client/src/components/marginals/TopBar.js
- client/src/components/portfolio/UserCard.js
- client/src/components/portfolio/Works.js
- client/src/screens/About.js
- client/src/screens/Article.js
- client/src/screens/Category.js
- client/src/screens/Contact.js
- client/src/screens/Expressions.js
- client/src/screens/Guide.js
- client/src/screens/Home.js
- client/src/screens/Live.js
- client/src/screens/PhotoStory.js
- client/src/screens/Podcast.js
- client/src/screens/Policy.js
- client/src/screens/SearchPage.jsx
- client/src/screens/SubCategory.js
- client/src/screens/UserProfile.js
> fix(style): fix website max width issue

- client/package.json
- client/src/pages/api/revalidate-article.js
- client/src/pages/api/revalidate.js
- client/yarn.lock
Fixes
Add on demand ISR for article
❤️Thank you!
> feat: add on demand ISR for article

- client/src/components/shared/ActivityIndicator.js
Fixes #236 
Remove placeholder blur from the activity indicator and reduce the size to 512 px.
❤️Thank you!
> fix: blur issue in activity indicator

- client/src/utils/determineCategory.js
Fixes the department tags issues
❤️Thank you!
> fix: categories department tags issues

- client/src/pages/portfolio/[userId]/[name].jsx
> fix: get noofarticle by articlelist

- README.md
Fixes
Added project reclamation link in readme file.
❤️Thank you!
> docs: add reclamation link

- client/src/components/marginals/DesktopNavbar.js
- client/src/components/marginals/Footer.js
- client/src/components/marginals/TopBar.js
- client/src/components/portfolio/UserCard.js
- client/src/components/portfolio/Works.js
- client/src/config/ApolloClient.js
- client/src/screens/About.js
- client/src/screens/Article.js
- client/src/screens/Category.js
- client/src/screens/Contact.js
- client/src/screens/Expressions.js
- client/src/screens/Guide.js
- client/src/screens/Home.js
- client/src/screens/Live.js
- client/src/screens/Podcast.js
- client/src/screens/Policy.js
- client/src/screens/SearchPage.jsx
> style: use default container width

- client/package.json
- client/src/assets/placeholder/onboarding.js
- client/src/components/onboarding/stages/Welcome.js
- client/src/config/ApolloClient.js
- client/src/config/firebase.js
- client/src/context/auth/AuthContext.js
- client/src/context/auth/AuthState.js
- client/src/pages/_app.jsx
- client/src/pages/admin/index.jsx
- client/src/pages/onboarding.jsx
- client/src/screens/Onboarding.js
- client/yarn.lock
> feat: user onboarding 

- client/src/screens/SubCategory.js
> style: use default container width in subcategory

- client/src/components/widgets/article/ArticleCardStack.js
- client/src/screens/Expressions.js
> style: fix expressions and article card width

- client/src/components/article/Header.js
- client/src/components/article/SidePanel.js
- client/src/components/categories/SectionTitle.js
- client/src/components/marginals/Footer.js
- client/src/components/podcast/BackLink.js
- client/src/components/portfolio/UserCard.js
- client/src/components/widgets/Title.js
- client/src/components/widgets/article/BigArticleCard.js
Fixes #263  
Cursor is changed from arrow to pointer at the required places.
❤️Thank you!
> fix: cursor pointer issue

- client/src/components/contact/Details.js
- client/src/components/contact/Feedback.js
Fixes #251 
Mobile view
❤️Thank you!
> Fix(styles): CSS issue in contact us

- client/src/config/firebase.js
> fix: firebase env vars is optional during build

- client/src/pages/portfolio/[...userId].jsx
> fix: ignore nulls in article array

- client/src/assets/placeholder/policy.js
- client/src/components/marginals/Footer.js
- client/src/components/policy/terms.js
- client/src/pages/policy.jsx
> fix : updated the terms and services content

- client/src/components/admin/subcomponents/AuthorCards.jsx
- client/src/components/admin/subcomponents/CategoryCards.jsx
- client/src/components/admin/subcomponents/FeaturedMedia.jsx
- client/src/components/admin/subcomponents/sharedMedia.js
- client/src/screens/admin/AddNew.js
> refactor: ui layout of addnew Page in Admin Panel

- client/src/components/widgets/DropDownCard.js
> feat: add dropdown card component

- client/src/config/firebase.js
> fix: firebase config error

- client/env/.env.sample
- client/src/config/firebase.js
- client/src/context/auth/AuthState.js
> chore(env): update env variables

- client/src/config/firebase.js
- client/src/context/auth/AuthState.js
> fix(firebase): setup config and add analytics

- client/src/assets/placeholder/article.js
- client/src/pages/[category]/[...subCategory].jsx
- client/src/screens/Category.js
> feat: add pagination to router

- client/src/assets/placeholder/healthAndEmergencyInfo.js
- client/src/components/contact/Details.js
- client/src/components/healthAndEmergencyInfo/Info.js
- client/src/components/widgets/DropDownCard.js
- client/src/pages/healthAndEmergencyInfo.jsx
- client/src/screens/HealthAndEmergency.js
> feat(guide): create Health and Emergency Info page

- client/src/components/article/ArticleTable.js
> fix: remove replaceall from table

- client/src/context/auth/AuthState.js
> chore: change profile pic store path

- client/src/components/article/ArticleTable.js
> fix: table first cell

- .firebaserc
- client/src/config/ApolloClient.js
- client/src/config/firebase.js
- client/src/context/auth/AuthState.js
- firebase.json
> feat: setup firebase emulator

- client/src/components/guide/calendar.js
- client/src/config/ApolloClient.js
- client/src/graphql/queries/article/listArticleByYearAndMonth.js
- client/src/pages/archive/[...yearAndMonth].jsx
- client/src/screens/Archive.jsx
> feat(graphql): archive page integration

- client/src/pages/expressions/[...subCategory].jsx
- client/src/screens/Expressions.js
(feat: add page base routing of subcategories #289)
Fixes
❤️Thank you!
> feat(expressions): add page base routing

- client/src/components/marginals/DesktopNavbar.js
- client/src/components/marginals/MobileNavbar.js
> feat: search bar ui

- README.md
> docs: add nextjs in readme

- README.md
- client/src/components/article/Header.js
bug: add null check in authors name #305
Fixes
❤️Thank you!
> fix(article): add null check for authorName

- client/src/components/marginals/Footer.js
> feat(footer): add go to archives section in footer

- client/src/components/expressions/PhotoStory.js
- client/src/components/expressions/Witsdom.js
- client/src/components/homepage/Banner.js
- client/src/pages/index.jsx
- client/src/screens/Home.js
> feat(home): integrate photostory and witsdom

- client/src/components/marginals/DesktopNavbar.js
- client/src/components/marginals/MobileNavbar.js
> fix: font family and search result condition

- client/src/screens/Home.js
> feat: show all articles of latest issue

- client/src/components/marginals/DesktopNavbar.js
- client/src/components/marginals/MobileNavbar.js
- client/src/graphql/queries/article/getAutoComplete.js
- client/src/hooks/useAutoComplete.js
> feat: auto complete suggestions on search bar

- README.md
> fix(docs): fix links used in images of readme file

- client/env/.env.sample
- client/package.json
- client/src/components/homepage/SocialMedia.js
- client/src/pages/index.jsx
- client/src/screens/Home.js
> feat(home): integrate youtube data api to fetch video meta data from a playlist

- client/src/screens/Home.js
> fix: photostory

- client/src/components/article/Content.js
- client/src/components/article/Disclaimer.js
> fix(article): remove uneven spaces in article paragraph

- client/src/components/expressions/SmallCard.js
- client/src/components/widgets/article/ArticleGrid.js
- client/src/components/widgets/article/BigArticleCard.js
- client/src/components/widgets/article/RegularArticleCard.js
- client/src/components/widgets/article/SmallArticleCard.js
- client/src/pages/expressions/index.jsx
- client/src/screens/Expressions.js
- client/src/utils/getRoutes.js
> feat(expressions): add Photostory in Expressions Page

- client/src/pages/[category]/[...subCategory].jsx
- client/src/screens/SubCategory.js
- client/src/utils/getLinks.js
- client/src/utils/getRoutes.js
> feat(subcategory): add department routing

- client/src/components/widgets/ClubInfoNavbar.js
> chore: fix prettier issue

- client/package.json
- client/src/components/widgets/PostHolder.js
- client/src/components/widgets/SubCategory.js
> fix: prettier format check

- client/src/pages/live.jsx
> fix: redirect live page to comingsoon

- client/src/components/widgets/SubCategoryLink.js
- client/src/screens/Category.js
- client/src/screens/SubCategory.js
> fix: live and department links

- client/src/components/marginals/DesktopNavbar.js
- client/src/hooks/useAutoComplete.js
> fix: autocomplete search-bar flickering

- client/src/components/article/Content.js
> fix: article overflow due to link

- client/src/screens/Home.js
> fix: add null check for article

- client/src/components/live/companyBanner.js
- client/src/components/live/courseSelector.js
- client/src/components/live/liveData.js
- client/src/components/live/nameFilter.js
- client/src/components/live/typeSelector.js
- client/src/screens/Live.js
> fix: set placed data in mobile screen

- client/src/components/article/ArticleTable.js
- client/src/components/article/Tags.js
- client/src/screens/Article.js
> fix(article): fix table data and max width of article

- client/src/components/portfolio/UserCard.js
- client/src/components/portfolio/Works.js
- client/src/pages/portfolio/[...userId].jsx
> fix: handle null contributions

- client/src/components/article/TableOfContent.js
> fix: alignment of table of content

- client/src/components/marginals/TopBar.js
- client/src/components/widgets/ToggleModeIcon.js
- client/src/config/themes/dark.js
- client/src/context/ThemeContext.jsx
- client/src/pages/_app.jsx
Fixes #402 
- Current Changing time :- 2000hrs 
❤️Thank you!
> feat: add dark theme context

- client/src/components/marginals/DesktopNavbar.js
- client/src/utils/getRoutes.js
> feat: remove cwc section

- client/src/components/guide/Options.js
- client/src/components/widgets/PostHolder.js
- client/src/components/widgets/SacInfoNavbar.js
- client/src/components/widgets/SocietyCards.js
- client/src/screens/Sac.js
> fix: add sac posts

- client/src/config/ApolloClient.js
- client/src/context/auth/AuthState.js
- client/src/utils/getAccess.js
- client/src/utils/getSpotifyAccessToken.js
> chore: remove url hardcoding

- client/src/pages/portfolio/[...userId].jsx
> fix: og tags of portfolio

- client/src/components/guide/Options.js
> fix(guide): add icon3 in option.js

- client/src/config/ApolloClient.js
- client/src/context/auth/AuthState.js
> fix: auth key errors

- client/src/components/marginals/MobileNavbar.js
> bug(theme): conflicting touch pad area

- client/yarn.lock
> chore: upgrade packages to latest minor-patch

- client/src/components/contact/Details.js
- client/src/components/contact/Feedback.js
- client/src/components/guide/Carousel.js
- client/src/components/guide/Options.js
- client/src/components/photostory/Carousel.js
- client/src/components/shared/button/BackButton.js
- client/src/components/widgets/BigCarousel.js
- client/src/components/widgets/article/ArticleGrid.js
> feat(theme): replace hard coded colors

- client/src/assets/placeholder/onboarding.js
- client/src/components/onboarding/stages/NewsletterSignup.js
- client/src/components/onboarding/stages/SelectTopics.js
- client/src/components/onboarding/stages/VerifyEmail.js
- client/src/components/onboarding/stages/Welcome.js
- client/src/config/ApolloClient.js
- client/src/config/imagekit.js
- client/src/context/auth/AuthState.js
- client/src/graphql/mutations/user/addNITRMail.js
- client/src/graphql/mutations/user/registerUser.js
- client/src/graphql/mutations/user/updateUserProfilePicture.js
- client/src/graphql/mutations/user/updateUserTopics.js
- client/src/screens/Onboarding.js
- client/src/utils/getAccess.js
- User flow for authentication (signup and sign in)
- User flow for webmail verification
❤️Thank you!
> feat: webmail authentication userflow

- client/src/components/categories/SectionTitle.js
- client/src/components/widgets/article/ArticleCarousel.js
> fix: darktheme styling issues

- client/src/components/onboarding/stages/VerifyEmail.js
- client/src/components/onboarding/stages/Welcome.js
- client/src/context/auth/AuthState.js
- client/src/graphql/queries/user/checkNITRMail.js
- client/src/screens/Onboarding.js
> feat: user onboarding experience

- client/src/assets/placeholder/contact.js
Fixes
CC information updated for the session 2023-24
❤️Thank you!
> chore: update CC info 2023

- client/src/pages/index.jsx
- client/src/screens/Home.js
> feat(home): increase number of displayed articles on the home page

- client/src/screens/Home.js
> fix(home): remove duplicate article in home page

- client/src/components/photostory/Carousel.js
> fix(photostory): optimise the state update in photostory

- client/src/components/admin_v2/Common/FeaturedMedia.jsx
- client/src/components/admin_v2/Common/Tags.jsx
- client/src/components/admin_v2/Marginals/Header.js
- client/src/components/admin_v2/issues/IssueDialogBox.jsx
- client/src/hooks/useAutoComplete.js
- client/src/hooks/useTagAutoComplete.js
- client/src/pages/admin_v2/addnew.jsx
- client/src/pages/admin_v2/browse.jsx
- client/src/pages/admin_v2/issues/index.jsx
- client/src/screens/admin_v2/AddNew.jsx
- client/src/screens/admin_v2/Browse.jsx
- client/src/screens/admin_v2/Edit.jsx
- client/src/screens/admin_v2/Issues.jsx
- client/src/utils/getAccess.js
> refactor: admin graphql client and auth

- client/src/components/onboarding/stages/Welcome.js
> fix: gsi call after script load
